"""PDF report generation for FabriSense analysis results."""

from __future__ import annotations

import os
import tempfile
from datetime import datetime
from typing import Any, Dict, Iterable

from fpdf import FPDF
from PIL import Image


class ReportGenerator:
    """Build a compact PDF report that mirrors the main app results."""

    def generate_pdf(self, analysis: Dict[str, Any], image: Image.Image) -> bytes:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(195, 91, 44)
        pdf.cell(0, 14, "FabriSense Analysis Report", new_x="LMARGIN", new_y="NEXT", align="C")

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(96, 90, 84)
        pdf.cell(
            0,
            7,
            f"Generated {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            new_x="LMARGIN",
            new_y="NEXT",
            align="C",
        )
        pdf.ln(4)

        image_path = self._write_temp_image(image)
        try:
            x_center = (210 - 90) / 2
            pdf.image(image_path, x=x_center, w=90)
        finally:
            if os.path.exists(image_path):
                os.remove(image_path)
        pdf.ln(6)

        llm = analysis.get("llm_analysis", {})
        palette = analysis.get("color_palette", {}).get("colors", [])

        self._section(pdf, "Fabric Type")
        fabric = llm.get("fabric_type", {})
        self._line(pdf, f"Primary: {fabric.get('primary', 'N/A')}")
        self._line(pdf, f"Subtype: {fabric.get('sub_type', 'N/A')}")
        self._line(pdf, f"Blend: {fabric.get('blend_composition', 'N/A')}")

        self._section(pdf, "Pattern and Texture")
        pattern = llm.get("pattern", {})
        texture = llm.get("texture", {})
        self._line(pdf, f"Pattern: {pattern.get('type', 'N/A')} / {pattern.get('sub_type', 'N/A')}")
        self._line(pdf, f"Texture: {texture.get('primary', 'N/A')}")
        self._line(pdf, f"Weight: {texture.get('weight', 'N/A')}")
        self._paragraph(pdf, f"Pattern notes: {pattern.get('description', 'N/A')}")

        self._section(pdf, "Quality")
        quality = llm.get("quality_assessment", {})
        self._line(pdf, f"Score: {quality.get('score', 'N/A')} / 10")
        self._line(pdf, f"Grade: {quality.get('grade', 'N/A')}")
        self._line(pdf, f"Durability: {quality.get('durability_estimate', 'N/A')}")
        self._bullet_lines(pdf, quality.get("factors", []))

        self._section(pdf, "Dominant Colors")
        for color in palette[:6]:
            self._line(pdf, f"{color['name']} {color['hex']} ({color['percentage']}%)")

        self._section(pdf, "Care Instructions")
        care = llm.get("care_instructions", {})
        self._line(pdf, f"Washing: {care.get('washing', 'N/A')}")
        self._line(pdf, f"Drying: {care.get('drying', 'N/A')}")
        self._line(pdf, f"Ironing: {care.get('ironing', 'N/A')}")
        self._paragraph(pdf, f"Special care: {care.get('special_care', 'N/A')}")

        self._section(pdf, "Styling Suggestions")
        for suggestion in llm.get("styling_suggestions", []):
            garment = suggestion.get("garment", "N/A")
            style = suggestion.get("style", "N/A")
            audience = suggestion.get("target_audience", "N/A")
            self._line(pdf, f"{garment}: {style} ({audience})")

        self._section(pdf, "Summary")
        self._paragraph(pdf, llm.get("overall_summary", "No summary available."))

        pdf.ln(6)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, "Generated by FabriSense AI for reference purposes.", align="C")

        output = pdf.output(dest="S")
        if isinstance(output, bytearray):
            return bytes(output)
        if isinstance(output, bytes):
            return output
        return output.encode("latin-1")

    def _write_temp_image(self, image: Image.Image) -> str:
        copy = image.copy()
        copy.thumbnail((900, 900), Image.Resampling.LANCZOS)
        handle = tempfile.NamedTemporaryFile(delete=False, suffix=".jpg")
        handle.close()
        copy.save(handle.name, format="JPEG", quality=92)
        return handle.name

    def _section(self, pdf: FPDF, title: str) -> None:
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(195, 91, 44)
        pdf.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(195, 91, 44)
        y = pdf.get_y()
        pdf.line(10, y, 200, y)
        pdf.ln(2)

    def _line(self, pdf: FPDF, text: str) -> None:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(45, 45, 45)
        pdf.cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")

    def _paragraph(self, pdf: FPDF, text: str) -> None:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(45, 45, 45)
        pdf.multi_cell(0, 6, text)

    def _bullet_lines(self, pdf: FPDF, items: Iterable[str]) -> None:
        for item in items:
            self._line(pdf, f"- {item}")
